-- =====================================================
-- Monitoramento Energético ESG
-- Estrutura inicial do banco de dados
-- =====================================================

-- Empresas ou unidades monitoradas
CREATE TABLE empresas (
    id_empresa NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    setor VARCHAR2(80),
    cidade VARCHAR2(80),
    estado CHAR(2),

    CONSTRAINT pk_empresas PRIMARY KEY (id_empresa)
);

-- Equipamentos responsáveis pelo consumo de energia
CREATE TABLE equipamentos (
    id_equipamento NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_empresa NUMBER NOT NULL,
    nome VARCHAR2(100) NOT NULL,
    categoria VARCHAR2(50),
    potencia_kw NUMBER(10,2),

    CONSTRAINT pk_equipamentos PRIMARY KEY (id_equipamento),
    CONSTRAINT fk_equipamentos_empresa
        FOREIGN KEY (id_empresa)
        REFERENCES empresas(id_empresa)
);

-- Registros de consumo energético
CREATE TABLE consumos (
    id_consumo NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_equipamento NUMBER NOT NULL,
    data_registro DATE DEFAULT SYSDATE NOT NULL,
    consumo_kwh NUMBER(12,2) NOT NULL,

    CONSTRAINT pk_consumos PRIMARY KEY (id_consumo),
    CONSTRAINT fk_consumos_equipamento
        FOREIGN KEY (id_equipamento)
        REFERENCES equipamentos(id_equipamento),

    CONSTRAINT ck_consumo_positivo
        CHECK (consumo_kwh >= 0)
);
